name: "[Tests] Acceptance Testing"

on:
  workflow_call: {}
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  tests:
    uses: istic/shared-workflows/.github/workflows/laravel-tests.yml@main
    with:
      php_versions: '["8.4", "8.5"]'
      node_version: "22"
      test_command: "vendor/bin/pest"
    secrets: inherit # pragma: allowlist secret
